### ISSUE TITLE
Sync killed in background

### ISSUE THREAD

**Issue by ZeroEkkusu** [fyears/remotely-save#12]
**Platform**: iOS

**Problem**:
When sync is started and the user switches apps for 5-10 seconds, the sync process most likely gets killed in the background, resulting in partial sync.

**Error messages**:
Displayed when I switch back to Obsidian
- `Remotely Save error while syncing`
- `Load failed`

**Proposed solution**:
Improve UX
After displaying `6/7 Remotely Save Sync data exchanging!`, hide the previous messages and make this one permanent, updating it whenever a file is synced to show the progress `🔄 Please wait, syncing 21 / 100`.

**Comment by fyears** [comment]
Thank you for your detailed report and suggestion.

1. The plugin is using js environment of Obsidian, and there's nothing I can do to avoid the app being killed due to the iOS apps restrictions... 
2. And the "showing progress" optimization is in my roadmap, I would like it to be a useful message while users click the switch ribbon icon while syncing.

**Comment by fyears** [comment]
https://github.com/fyears/remotely-save/releases/tag/0.2.11

Users can click the sidebar-ribbon while syncing, then the notice would show how many files of total files have been synced.
