### ISSUE TITLE
[Feature Request] sftp support

### ISSUE THREAD

**Issue by pcause** [fyears/remotely-save#16]
It would be great to support sftp for remote save.  There is a javascript library for ssh2 access that handles password and key based login

**Comment by fyears** [comment]
I would like to implement it very much, but I am sorry it’s blocked by some technical limitations IMO.

Mobile support is “the-must” by this plugin’s design. It means that, the plugin is limited to browser environment instead of nodejs environment. Unfortunately, ssh2 library only works in nodejs environment and it seems to be technically impossible to make it work in pure-browser environment. 

So I am afraid the feature is hard, if not impossible, to be implemented.

**Comment by exoticknight** [comment]
maybe we can consider https://github.com/billchurch/webssh2 ？

**Comment by fyears** [comment]
The problem is that ssh requires “raw tcp data”. On browser the only potentially possible way is using websocket.

**Comment by exoticknight** [comment]
ws needs http to upgrade protocol
 first, so it's still impossible
