### ISSUE TITLE
[Feature request] Automatic synchronization when closing the program 

### ISSUE THREAD

**Issue by ivanmood0** [fyears/remotely-save#21]
Probably the most useful Obsidian plugin for me. It would be great if there was a possibility of automatic synchronization when closing the application.

I also want to note:

At the expense: "Deletion operation can only be triggered from local device. It's because of the "minimal intrusive design". May be changed in the future", I think if you added the **optional option** to delete not only from the local device, but also from synchronization services, so that when synchronizing devices, the file is deleted on both devices, it will be cool.

The same goes for: "All files or folder starting with . (dot) or _ (underscore) are treated as hidden files, and would NOT be synced. It's useful if you have some files just staying locally. But this strategy also means that themes / other plugins / settings of this plugin would neither be synced", the **optional** ability to sync hidden folders would also not be superfluous. 

Even with all these nuances, this plugin can easily be called: **ObsidianSync**

Thank you very much for the wonderful work.

**Comment by fyears** [comment]
1. sync when closing Obsidian: I’d love to, but it might be unreliable or even impossible. Because the plugin treats Obsidian as a special web browser and makes use of its environment. You know, users are literally unable to run scripts on the website if they close the browser…
2. deletion sync: tracked in https://github.com/fyears/remotely-save/issues/6 it’s kind of hard, becasue a correct algorithm needs to deal with lots of corner cases.
3. not ignoring dot files: in the plan, tracked in https://github.com/fyears/remotely-save/issues/9 . No so soon though.
4. renaming: the plugin will never be renamed to Obsidian sync, because it conflicts the name of the official product of Obsidian. In fact, I deliberately avoid the word “sync” in the name from the beginning.

Thank you for your reports! And if you have any other suggestions, feel free to open another issue!

**Comment by ivanmood0** [comment]
> 1. sync when closing Obsidian: I’d love to, but it might be unreliable or even impossible. Because the plugin treats Obsidian as a special web browser and makes use of its environment. You know, users are literally unable to run scripts on the website if they close the browser…
> 2. deletion sync: tracked in [Delete can not be synced #6](https://github.com/fyears/remotely-save/issues/6) it’s kind of hard, because a correct algorithm needs to deal with lots of corner cases.
> 3. not ignoring dot files: in the plan, tracked in [ignoring of files and folders starting with . and _ ? #9](https://github.com/fyears/remotely-save/issues/9) . No so soon though.
> 4. renaming: the plugin will never be renamed to Obsidian sync, because it conflicts the name of the official product of Obsidian. In fact, I deliberately avoid the word “sync” in the name from the beginning. And this plugin will never be a full replacement to, or as powerful as, the official product.
> 
> Thank you for your reports! And if you have any other suggestions, feel free to open another issue!

1. I think it is better to be unreliable than to have no such an option at all, just don't count on it too much, but if you forgot to sync, there will be at least some chance that the synchronization took place automatically, I did not delve into the api Obsidian, but maybe you can cause some of its service at closing, and in the meantime synchronization would be carried out, I don't know, that's the first thing that came to mind, as an option, can of course try to track changes in the files and automatically synchronize after each change, but I think this is also not too easy, trivial task.

2. Thank you, got it, I will open another branch with a function, which follows somewhat from this.

3. Ok., I look forward to it.

4. Here you did not quite understand what I meant, I just wanted to emphasize that this is a very powerful solution (which is not much inferior to the built-in synchronization function in the Juplin, which has been developing for quite some time), and which can proudly even be called ObsidianSync (do not rename) 🙃
