### ISSUE TITLE
Only upload a small amount of files when use one drive

### ISSUE THREAD

**Issue by quanru** [fyears/remotely-save#22]
![image](https://user-images.githubusercontent.com/11739753/150734278-b3fa479b-ce46-43db-a868-39e9086c3767.png)

![image](https://user-images.githubusercontent.com/11739753/150733561-b6331d0b-68bb-4d1c-bea5-7e5e803e9c61.png)

**Comment by fyears** [comment]
Again, no idea what happened... :-( But let's figure it out....

1. The most suspicious problem is from your first screenshot. The plugin called msft api, but failed because of the CORS issue. It's quite strange, because the same api works on my side! (Both Windows desktop and my mobile phone.) 

    This api (`:/createUploadSession`) is called if you were going to upload a large file. I tried to upload a large file by myself and no problem was met.

    Could you again try to reproduce the issue in another testing vault? Without installing any other plugins (even the official ones, read on.)

    ![91f6b0d1d29649d32429324da767b18](https://user-images.githubusercontent.com/1142836/150833482-acb7c314-b383-47a5-832e-c270aeb32955.png)
    ![2c5c64bc09975dadbb11b4eda07d323](https://user-images.githubusercontent.com/1142836/150834219-2d9f56c6-f61c-424e-856e-35816bf8af16.png)


2. The next screenshots are **NOT** relevant. I searched through my plugin, and was sure that my plugin doesn't contain any words that exactly matches "Start syncing" or "StartAutoSync: this.timeoutIDAutoSync". (You **can** also search them by yourself on GitHub!) So the errors in the 2nd and later screenshots should not be remotely-save's issue.

**Comment by fyears** [comment]
A new version tries to avoid cors as much as possible while using onedrive api:

https://github.com/fyears/remotely-save/releases/tag/0.2.14
