### ISSUE TITLE
Track the movement of files/directories to duplication avoid

### ISSUE THREAD

**Issue by ivanmood0** [fyears/remotely-save#23]
It would be nice to track the movement of files/directories to avoid duplication, what i mean is if you create some file, sync it between devices, and then move the file to some folder then you just get a duplicate file, not move it, that is, you will already have two identical files, just  in different places, of course, you can first move the file to the desired directory, and then synchronize, or if you have already synchronized to move the file on both devices, but agree, this is not very convenient.

**Comment by fyears** [comment]
> I changed a word in a file on my desktop and found that it was not being reflected on my iPad, no matter how many times I synced both devices. Then I moved the file to an

1. Firstly you could directly check the content on s3 to get whether it was uploaded successfully.
2. Secondly Obsidian caches the file for a while and then save it to the disk automatically. If you sync before the file was saved to the disk, the of course the plugin was aware of the changes.
3. Thirdly your operating system might also incorrectly not set the modified time to a new one. In another issue some user reported this behavior.
4. Fourthly, you could go to the settings of this plugin, scroll down to the end, and you would see a “debug” session. In there, you could see a “export sync plans” subsession. Click the export button, and a record file and a folder `_debug_remotely_save` will be generated under your vault. In the file you could see the “plan”, the decision (upload or download or skip), and the modified time locally and remotely, of each file. Maybe you could find some clues there.

**Comment by NAL100** [comment]
> > I changed a word in a file on my desktop and found that it was not being reflected on my iPad, no matter how many times I synced both devices. Then I moved the file to an
> 
> Thabk you for your report.

The debug (although very lengthy and time consuming) would seem to provide clues on why something is deciding to be synced or not. However I am now getting many issues with duplicate files.

How it typically works is that I am using my Mac/PC desktop primarily, and I end up changing files or moving them. Then I sync it with S3 bucket, and the S3 bucket changes.

Then I go to my iPhone or iPad and try to sync, and **it uploads the old versions** (that are on the mobile devices) to the S3 bucket, and if I'm not careful it will also sync them to my PC/Mac due to automatic sync. So now I have to manually remove the files from multiple places, resync etc.

This would be avoided if the mobile devices were constantly in sync with the desktop devices, however they only sync when I open them and ask them to sync. Effectively there are no duplicates being removed. I have already deleted and reuploaded the entire contents of the s3 folder multiple times.

**Comment by fyears** [comment]
> The debug (although very lengthy and time consuming) would seem to provide clues on why something is deciding to be synced or not.

https://github.com/fyears/remotely-save/blob/master/docs/sync_algorithm.md

**Comment by NAL100** [comment]
@fyears 
> So the main point is that you usually rename files or folders.
> 
> 1. Renaming is treated as deleting and creating. And currently deleting is not synced across devices, due to this https://github.com/fyears/remotely-save/blob/master/docs/minimal_intrusive_design.md . 
> 
> Anyways, I would develop a solution to the first point (deleting operations being synced) So at least no duplicated files on s3

It seems like if you can track deletes then effectively you are also tracking renames, so I think this would be great if it could be developed soon. Right now the software isn't very practically usable for me unless I am very careful, since when my database gets bigger (I now have ~2000 notes), I can't go through and manually compare which got synced or not, and fixing errors is taking a lot of time. Thanks for your work on this!

**Comment by fyears** [comment]
Hi a new version 0.3.0 supports deletions sync. Please give it a try! (But remember to back up your vault firstly) It should at least resolve the “duplicated files after renaming” for a little bit.

**Comment by fyears** [comment]
And, for the “tracking renaming to avoid reuploading”, that’s really a hard technical problem. 

For example, what should the plugin do if a user renames the file A to B on the first device and renames A to C on the second device?  What if a user renames A to B and makes some modifications and renames B to C? Things will quickly become messy. 

And even the official Obsidian Sync just reupload the files. 

I will keep paying attention to potential solutions, but I am afraid the newer algorithm will bot be implemented in the near future.

**Comment by NAL100** [comment]
> And, for the “tracking renaming to avoid reuploading”, that’s really a hard technical problem.
> 
> For example, what should the plugin do if a user renames the file A to B on the first device and renames A to C on the second device? What if a user renames A to B and makes some modifications and renames B to C? Things will quickly become messy.

Great, thanks for the new version! I will check it out.

For your question, here is what I would like to happen.

1) If a user renames from A to B on first device, but A to C on a second device, then a conflict file should be generated, with the difference between the B and C newly created files.

2) For renaming A-B, modifying and then renaming B-C, the log would show:

A deleted, B created, B modified (saved), B deleted, C created.

I'm not sure where the issue is there. It seems to just be rename, save, rename.

A lot of this in terms of syncing likely depends on timing. So perhaps introduce an optional waiting period being syncing begins.
