### ISSUE TITLE
If the file name is special, it will fail to synchronize and prompt 404

### ISSUE THREAD

**Issue by appdev** [fyears/remotely-save#5]
I have a few image files and they are named like this. When syncing, it prompts 404. 
I am using WebDav

like this：

`watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L3FxXzQxNDUzMjg1,size_16,color_FFFFFF,t_70-10.png`
![屏幕截图 2021-12-26 181517](https://user-images.githubusercontent.com/9107717/147405216-9f5265b6-3078-433b-9fa2-889dd29f6a3e.png)

<!— second screenshot deleted ->

**Comment by fyears** [comment]
It seems that you’ve enabled password, so the file name has been converted to a string full of letters and numbers.

Could you please try to click “check connectivity” and check the errors in console?

![3CC4C802-8FBC-45CA-B2B5-323444BDD574](https://user-images.githubusercontent.com/1142836/147406389-15c152d9-a198-4a77-8a17-ecdeaf1dc39e.jpeg)

**Comment by fyears** [comment]
(And I edited your comment to remove the second screenshot because you have not hidden your host information…)

**Comment by appdev** [comment]
The WebDav connection is working fine. I have tested it and if I delete files with special names, it syncs properly. Thanks for the heads up, this is a test server and I have shut down the WebDav service.
![屏幕截图 2021-12-26 181517](https://user-images.githubusercontent.com/9107717/147409339-76396261-1457-4322-aa89-17c2910077f7.png)

**Comment by fyears** [comment]
OK, I will try to reproduce it and figure out what's wrong

**Comment by fyears** [comment]
I figured out what happened...

It not about any file name characters, but it's about the file name **length**.

If you set a password, the file path in vault is also encrypted using your password, then is `base32`-ed. Unfortunately, the encrypted file path length would [be increased to 160%](https://en.wikipedia.org/wiki/Base32). Another limitation comes from the file system that a file name has [max length](https://serverfault.com/questions/9546/filename-length-limits-on-linux) on each platform.

And your "special file" name is already very long, so after the encryption, the new even-longer file name cannot be successfully created on target webdav server.

I am sorry that there is not much I can do. In the near future I will use `base64url` instead of `base32`, so the size explosion will not be as serious as it's now.

**Comment by fyears** [comment]
base64 is implemented in https://github.com/fyears/remotely-save/commit/1bc6ba4b018741fe06eb62f78cbf101d137a15e5 . It will come in next version in the near future.
