### ISSUE TITLE
Delete can not be synced

### ISSUE THREAD

**Issue by Royalsus** [fyears/remotely-save#6]
fyears I like your plugin very much, but I have a problem with it. I use Obsidian both on Windows and my Andorid Mobile. When I delete some files on Windows and then I use your plugin to sync, it can delete these files on my S3 service. But then I want to sync on my Andorid device to delete the same files,these files can not be delete, it still remains on Obsidian, and my sync operation on the Andorid device will sync these files to the S3 service.Is there any way to solve that？Thank you so much.

**Comment by fyears** [comment]
I understand your intention. 

It's a limitation of current design: because the plugin does not upload any extra meta data to S3, your Android device has no way to distinguish between "newly-added LOCAL files" and "already deleted REMOTE files". To avoid potential data loss, I choose to prefer uploading files right now. More details [in the doc](https://github.com/fyears/remotely-save/blob/master/docs/minimal_intrusive_design.md).

I am planning to make the plugin upload an extra file recording "files having been deleted" to S3, so "deletion status" could be synced across devices. Right now you have to manually delete the files in your different devices, sorry.

**Comment by ZeroEkkusu** [comment]
Just to make this clear:

1. Sync all devices
2. Delete the file from all devices
3. Sync all devices, again

Otherwise, the file will keep coming back if it remains on one or more devices and you sync those devices next time.

**Comment by fyears** [comment]
@ZeroEkkusu 

Yes you are right. I am planning to develop a v2 algorithm to sync deletions.

**Comment by fyears** [comment]
Hi a new version 0.3.0 supports deletions sync. Please give it a try! (But remember to back up your vault firstly)
