### ISSUE TITLE
WebDAV served by RClone not supported ?

### ISSUE THREAD

**Issue by nohappiness** [fyears/remotely-save#7]
I have a self-hosted webdav server which is running by [rclone](rclone.org), and I after set up in RemotelySave settings page, my server did not receive any request. Is this a CROS related issue or something else is wrong?

RClone command:
`rclone serve webdav /home/webdav --cert cert.pem --key key.pem --user xxx --pass xxxxxx --addr :3088 --log-level DEBUG`

RemotelySave settigns:
Server: https://myserver-name.com:3088/
Server username: xxx
Server password: xxxxxx

When I click "check" button, nothing output in rclone logs, I'm totally confused now, please help Orz

**Comment by fyears** [comment]
I am sorry, but indeed it's a CORS issue.

1. You can check the Obsidian log by pressing keys: Ctrl+Shift+I (the letter i) on Windows/Linux, Command+Shift+I on Mac. You should see something like this: 
    
    ![xxxxx](https://user-images.githubusercontent.com/1142836/147690257-d012ac07-0643-4b3a-9c25-5ccc2b9c2616.png)

    As you guessed, the plugin is blocked by CORS. So after the "Checking..." Notice, no "Great! The webdav server can be accessed." notice followed. (A better notice is needed though)

2.  I search around rclone docs, only one potential param `--rc-allow-origin` was found. **HOWEVER**, I tried something like `--rc-allow-origin "*"` or `--rc-allow-origin "app://obsidian.md"`, **None** of them works. 

    I also manually construct a `PROFIND` http request to the address, and no `Access-Control-Allow-Origin` was responded so CORS is still an issue. 

    I am not sure whether there's something I ignored or this parameter doesn't work with `rclone serve`. You are welcome to continue to give it a try can report any successful ways......

3. The plugin will not provide a way to bypass CORS in the near future because of the technical difficulty  and limitations of Obsidian api currently. I am sorry.

**Comment by fyears** [comment]
For those who still reading this: it's already supported in Obsidian>=0.13.25 AND latest version of the plugin.
